CREATE TABLE fss_run_table (
  RUNID           NUMBER PRIMARY KEY NOT NULL,
  RUNSTART        DATE,
  RUNEND          DATE,
  RUNOUTCOME      VARCHAR2(16),
  REMARKS         VARCHAR2(255)
);

CREATE TABLE parameter (
  KIND              VARCHAR2(25 BYTE),
  CODE              VARCHAR2(25 BYTE),
  VALUE             VARCHAR2(255 BYTE),
  DESCRIPTION       VARCHAR2(255 BYTE),
  ACTIVE            VARCHAR2(1 BYTE),
  AUDIT_DATE        DATE DEFAULT sysdate
);

CREATE TABLE fss_daily_transaction (
  TRANSACTIONNR     NUMBER PRIMARY KEY NOT NULL,
  DOWNLOADDATE      DATE,
  TERMINALID        VARCHAR2(10),
  CARDID            VARCHAR2(17),
  TRANSACTIONDATE   DATE,
  CARDOLDVALUE      NUMBER,
  TRANSACTIONAMOUNT NUMBER,
  CARDNEWVALUE      NUMBER,
  TRANSACTIONSTATUS VARCHAR2(1),
  ERRORCODE         VARCHAR2(25),
  TRANSACTIONSEQ    VARCHAR2(15)
);

CREATE TABLE fss_daily_settlement (
  RECORDTYPE        NUMBER,
  BSB               VARCHAR2(6),
  ACCOUNTNR         VARCHAR2(10),
  TRAN_CODE         NUMBER,
  SETTLEVALUE       NUMBER,
  MERCHANTID        NUMBER,
  MERCHANTTITLE     VARCHAR2(32),
  BANKFLAG          VARCHAR2(3),
  LODGEMENTNR       VARCHAR2(15),
  TRACE             VARCHAR2(16),
  REMITTER          VARCHAR2(16),
  GSTTAX            VARCHAR2(8),
  CREATED           DATE
);